# Generated by Django 3.2.9 on 2021-11-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('article_header', models.CharField(max_length=256)),
                ('article_content', models.TextField()),
                ('article_date', models.DateField(editable=False)),
                ('article_last_updated', models.DateTimeField(editable=False)),
                ('article_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_created', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentQuoteModel',
            fields=[
                ('author', models.CharField(max_length=24)),
                ('quote', models.TextField(max_length=256)),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
