# Generated by Django 3.2.9 on 2021-11-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='article_last_updated',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
