# Generated by Django 3.2.9 on 2021-11-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20211122_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='article_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
