# Generated by Django 3.2.9 on 2021-11-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_articlemodel_article_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='article_file',
            new_name='article_cover_art',
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='article_slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
