# Generated by Django 3.2.9 on 2021-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20211125_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='article_cover_art',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='article_resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='article_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
