# Generated by Django 3.2.9 on 2021-11-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20211126_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='article_cover_art',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
