# Generated by Django 3.2.9 on 2021-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20211129_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(to='sites.Tags'),
        ),
    ]
