# Generated by Django 3.2.9 on 2021-11-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_alter_articlemodel_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
