# Generated by Django 3.2.9 on 2021-11-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sites.Tag'),
        ),
    ]
