# Generated by Django 3.2.9 on 2021-11-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_alter_articlemodel_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagModel',
        ),
    ]
