# Generated by Django 3.2.9 on 2021-11-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_rename_tag_tagmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quote', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TradingDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
