# Generated by Django 3.2.9 on 2021-11-29 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_auto_20211129_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingdaymodel',
            name='trades',
        ),
        migrations.AddField(
            model_name='tradingdaymodel',
            name='trades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.trademodel'),
        ),
    ]
