# Generated by Django 3.2.9 on 2021-11-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_auto_20211129_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingdaymodel',
            name='trades',
        ),
    ]
