# Generated by Django 3.2.9 on 2021-11-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_remove_tradingdaymodel_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingdaymodel',
            name='day',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
