# Generated by Django 3.2.9 on 2021-11-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_tradingdaymodel_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingdaymodel',
            name='trades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trade', to='sites.trademodel'),
        ),
    ]
