# Generated by Django 3.2.9 on 2021-11-29 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_tradingdaymodel_trades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdaymodel',
            name='trades',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.trademodel'),
        ),
    ]
