# Generated by Django 3.2.9 on 2021-11-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0018_alter_tradingdaymodel_trades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='tradingdaymodel',
            name='trades',
        ),
        migrations.DeleteModel(
            name='TradeModel',
        ),
        migrations.DeleteModel(
            name='TradingDayModel',
        ),
    ]
