# Generated by Django 3.2.9 on 2021-11-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0021_auto_20211129_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingday',
            name='trading_date',
            field=models.DateField(unique=True),
        ),
    ]
