# Generated by Django 3.2.9 on 2021-11-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0022_alter_tradingday_trading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingday',
            name='end_of_day_balance',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trademodel',
            name='trading_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='sites.tradingday'),
        ),
    ]
