# Generated by Django 3.2.9 on 2021-12-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0024_trademodel_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='is_winner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trademodel',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
