# Generated by Django 3.2.9 on 2021-12-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0026_alter_trademodel_profit_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='is_winner',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='trademodel',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
