# Generated by Django 3.2.9 on 2021-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0027_auto_20211208_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
