# Generated by Django 3.2.9 on 2021-12-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0028_articlemodel_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='read_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
