# Generated by Django 3.2.9 on 2021-12-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0030_alter_articlemodel_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingday',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
