# Generated by Django 3.2.9 on 2021-12-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0031_tradingday_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.tagmodel'),
        ),
    ]
