# Generated by Django 3.2.9 on 2021-12-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0032_auto_20211227_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='tags',
            new_name='tag',
        ),
    ]
